[package]
edition = "2021"
name = "willbot-koishi_jieba"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi        = { version = "2.12.2", default-features = false, features = ["napi4"] }
napi-derive = "2.12.2"
jieba-rs    = { version = "0.6", features = ["default-dict", "tfidf", "textrank"] }

[build-dependencies]
napi-build = "2.0.1"

[profile.release]
lto = true
